autenticacao/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path("get_perfis/", views.get_perfis, name="get_perfis"),
    path("logout/", views.logout, name="logout"),
    path('password_reset/', views.MyPasswordReset.as_view(),name='password_reset'),
    path('password_reset/done/', views.MyPasswordResetDone.as_view(),name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',
        success_url=reverse_lazy('autenticacao:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
]

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path("main", views.main, name="main"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.deletion import ProtectedError

class Departamento(models.Model):
    nome = models.CharField(max_length=500)
    sigla = models.CharField(max_length=30)
    
    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este departamento, pois ele possui usuarios vinculados.",
                self
            )
        super().delete(*args, **kwargs)
        
    def __str__(self):
        return self.nome

class Perfil(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este perfil, pois ele possui usuarios vinculados.",
                self
            )
        super().delete(*args, **kwargs)
        
    def __str__(self):
        return self.nome
    
class UsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None):
        if not email:
            raise ValueError('O usuário deve ter um endereço de e-mail')
        user = self.model(email=self.normalize_email(email), nome=nome)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password=None):
        user = self.create_user(email, nome, password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser):
    nome = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT)
    perfis = models.ManyToManyField(Perfil)

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def tem_perfil(self, perfil_nome):
        return self.perfis.filter(nome=perfil_nome).exists()

sistema/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from django.urls import reverse_lazy
from cadastros.models import Usuario
from django.contrib.auth.views import PasswordResetView

def login(request):
    if request.method == 'POST':
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtSenha')
        perfil_id = request.POST.get('slcPerfil')

        usuario = authenticate(request, username=email, password=senha)
        
        if usuario is not None and perfil_id:
            perfis_usuario = usuario.perfis.filter(id=perfil_id)
            if perfis_usuario.exists():
                #limpa as sessoes do usuario
                request.session.flush()
                #cria a sessao do usuario
                auth_login(request, usuario)
                
                request.session['id_atual'] = usuario.id
                request.session['email_atual'] = usuario.email
                request.session['departamento_id_atual'] = usuario.departamento.id
                request.session['departamento_nome_atual'] = usuario.departamento.nome
                request.session['departamento_sigla_atual'] = usuario.departamento.sigla                      
                request.session['perfil_atual'] = perfis_usuario.first().nome                
                request.session['perfis'] = list(usuario.perfis.values_list('nome', flat=True))
                
                #configura sessao para expirar em 4 horas
                request.session.set_expiry(14400)
                
                messages.success(request, 'Login realizado com sucesso!')
                
                #no futuro iremos separar em diferentes paginas
                if request.session.get('perfil_atual') in {'Administrador', 'Estoquista', 'Vendedor'}:
                    return redirect('core:main')
                
            else:
                messages.error(request, 'Perfil inválido para este usuário.')
        else:
            if usuario is None:
                messages.error(request, 'Senha incorreta.')
            else:
                messages.error(request, 'Usuário ou senha inválidos.')
            
    return render(request, 'login.html')

def get_perfis(request):
    email = request.GET.get('email', '')
    perfis = []
    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        perfis = usuario.perfis.all().values('id', 'nome')
        data = {'perfis': list(perfis), 'usuario_existe': True}
    else:
        data = {'usuario_existe': False}
    return JsonResponse(data)

def logout(request):
    #limpa a sessao ao deslogar
    request.session.flush()
    auth_logout(request)
    
    messages.success(request, 'Logout realizado com sucesso.')
    return redirect('autenticacao:login')

class MyPasswordReset(PasswordResetView):
    template_name = 'password_reset_form.html'
    email_template_name = 'password_reset_email.html'
    subject_template_name = 'password_reset_subject.txt'
    success_url = reverse_lazy('autenticacao:password_reset_done')

class MyPasswordResetDone(PasswordResetView):
    template_name = 'password_reset_done.html'

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def main(request):
    return render(request, "main.html")

sistema/views.py
from django.shortcuts import render

# Create your views here.

autenticacao/templates/login.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
            <div id="divEmailError" class="error-message"> </div>
        </div>
        <div class="form-group hidden-group" id="divSenha">
            <label for="txtSenha">Senha</label>
            <input type="password" class="form-control" id="txtSenha" name="txtSenha" required autocomplete="new-password">
        </div>
        <div class="form-group hidden-group" id="divPerfil">
            <label for="perfil">Perfil</label>
            <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
        </div>
        <div id="divSpace" class="space"> </div>
        <button type="submit" class="btn btn-light">Entrar</button>
        <a href="{% url 'autenticacao:password_reset'%}"  class="btn btn-light">Esqueci minha senha</a>
    </form>
</div>

<script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#slcPerfil').empty();
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            if (data.perfis.length > 0) {
                                $('#slcPerfil').empty();
                                data.perfis.forEach(function(perfil) {
                                    $('#slcPerfil').append(new Option(perfil.nome, perfil.id));
                                });
                                $('#divPerfil').removeClass('hidden-group');
                                $('#divSenha').removeClass('hidden-group');
                            } else {
                                toastr.error("Nenhum perfil encontrado para este e-mail.", "Erro");
                            }
                        } else {
                            $('#divEmailError').text('.').addClass('visible');
                        }
                    }
                });
            }
        });

        $('#btnEsqueciSenha').click(function(event) {
            event.preventDefault();
            toastr.info('Se você esqueceu sua senha contate o administrador do sistema.');
        });
    });
</script>
{% endblock %}

autenticacao/templates/password_reset_complete.html
{% extends "index.html" %}

{% block conteudo %}
    <h1>Senha redefinida com sucesso</h1>
    <p>Sua senha foi redefinida com sucesso. Você pode fazer o login com a nova senha.</p>
    <a href="{% url 'autenticacao:login' %}">Fazer login</a>
{% endblock%}

autenticacao/templates/password_reset_confirm.html
{% extends 'index.html' %} 
{% load widget_tweaks %} 
{% block conteudo %}
<div class="container">
  <h2>Escolha uma Nova Senha</h2>
  <p class="message">
    Digite sua nova senha abaixo para redefinir o acesso à sua conta.
  </p>
  <form method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <span class="input-group-text" id="basic-addon1">
        <i class="fa-solid fa-lock"></i>
      </span>
      {{ form.new_password1|add_class:"form-control"|attr:"placeholder:Digite a nova senha" }}
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text" id="basic-addon1">
        <i class="fa-solid fa-lock"></i>
      </span>
      {{ form.new_password2|add_class:"form-control"|attr:"placeholder:Confirme a nova senha" }}
    </div>
    <button type="submit" class="btn btn-light">Redefinir Senha</button>
  </form>
</div>
{% endblock %}

autenticacao/templates/password_reset_done.html
{%extends 'index.html'%}
{% block conteudo %}
<div class="container">
    <h2>Redefinição de senha</h2>
    <p class="message">
        Um email foi enviado para você com as instruções para redefinir sua senha.
    </p>
    <p class="message">Por favor verifique sua caixa de email. </p>
    <a href="{% url 'autenticacao:login'%}" class="btn btn-light">  
        Voltar para a página de login
        
    </a>

</div>
{% endblock %}

autenticacao/templates/password_reset_email.html
{% load i18n %}
{%autoescape off%}
{%blocktranslate%}Voce esta recebendo este e-mail porque você solicitou a redefinição da sua senha no site {{ site_name }}.{%endblocktranslate%}

{% translate "Por favor va para pagina e escolha uma nova senha. " %}
{%block reset_link%}
{{ protocol }}://{{ domain }}{% url 'autenticacao:password_reset_confirm' uidb64=uid token=token %}
{% endblock%}

{% translate "Se você não solicitou a redefinição da senha, por favor, ignore este e-mail." %}

{% translate "Obrigado por usar nosso site." %}

{% translate "A equipe de suporte" %}
{%endautoescape%}

autenticacao/templates/password_reset_form.html
{% extends 'index.html' %}
{% block conteudo %}
<div class="container">
    <h2>Redefinir senha</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email" class="form-control" id="id_email" name="email"
            required
             autocomplete="off"
             placeholder="Digite seu email">
        </div>
        <button type="submit" class="btn btn-light">Enviar</button>
    </form>
    <div class="mt-3">
        <a href="{% url 'autenticacao:login' %}" class="btn btn-light">Voltar a login</a>
    </div>
</div>
{% endblock %}

core/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:: PYPEL ::</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid vh-100 d-flex flex-column">
        <div class="row flex-grow-1">
            <div class="col col-blue d-flex flex-column justify-content-center" style="background-color: #efc9c9">
                <!-- Conteúdo carregado dinamicamente -->
                <div class="content">
                    {% block conteudo %}
                    {% endblock %}
                </div>
            </div>
            <div class="col col-white d-flex flex-column justify-content-center align-items-center">
                <div class="text-center">
                    <img src="{% static 'img/logo.png'%}" alt="Logomarca do Sistema de Gerenciamento de Papelaria" width="300px">
                    <div class="footer-text text-center py-3">
                        Este sistema está licenciado sob 
                        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer" style="color: #0000FF;">
                            Licença Creative Commons&copy; 4.0 
                        </a> 
                        <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons"> <br>
                        Disponível para download em 
                        <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer" style="color: #0000FF;">
                            github.com/ciniro/pypel
                        </a>
                        <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
                        <button id="btnSobre" class="btn btn-outline-secondary p-0">Sobre</button>
                    </div>
                </div>
            </div>
        </div>
    </div>    
    
    <!-- sobre -->
    <div class="modal fade" id="jnlSobre" tabindex="-1" role="dialog" aria-labelledby="jnlSobreRotulo" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="jnlSobreRotulo">Sobre o PYPEL</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-justify">
                    <p>
                        O PYPEL é um sistema de gerenciamento de papelaria que permite a gestão do estoque de produtos 
                        fornecendo um sistema de entrada e uma tela de venda que permite dar saída nos itens cadastrados no estoque.
                    </p>
                    <p>
                        O sistema é utilizado pelo Prof. Dr. Ciniro Nametala (<a href="http://lattes.cnpq.br/3258604768114823">lattes</a>) 
                        com o apoio das turmas da disciplina de Programação WEB do curso de Bacharelado em Engenharia de Computação do Instituto Federal de Minas Gerais - <i>Campus</i> Bambuí, e está licenciado sob 
                        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
                            Licença Creative Commons&copy; 4.0 
                        </a> 
                        <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons">.
                    </p>
                    <p>
                        O PYPEL foi desenvolvido em <a href="https://www.python.org/" target="_blank" rel="noopener noreferrer">
                            Python
                        </a> <img src="{% static 'img/python.png' %}" width="15px" alt="Python">, 
                        <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django</a>
                        <img src="{% static 'img/django.png' %}" width="15px" alt="Django"> e 
                        <a href="https://www.postgresql.org/" target="_blank" rel="noopener noreferrer">PostgreSQL</a>
                        <img src="{% static 'img/postgresql.png' %}" width="15px" alt="PostgreSQL">. 
                        O código fonte, juntamente com as instruções de instalação, estão disponíveis para <i>download</i> em 
                        <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer">
                            github.com/ciniro/pypel
                        </a>
                        <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">. Você pode contribuir com o projeto, reportando erros, sugerindo melhorias ou mesmo implementando novas funcionalidades você mesmo. Por favor, use o GitHub para isso.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "3000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        toastr.error("{{ message }}", "Erro");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        toastr.success("{{ message }}", "Sucesso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        toastr.warning("{{ message }}", "Aviso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        toastr.info("{{ message }}", "Atenção");
                    {% endif %}
                {% endfor %}
            {% endif %}

            //sobre
            $('#btnSobre').click(function() {
                $('#jnlSobre').modal('show');
            });
        });
    </script>

</body>
</html>

core/templates/main.html
{% extends 'master.html' %}

{% load static %}

{% block conteudo %}
<div>
    <img src="{% static 'img/background.png'%}" 
        alt="Logomarca do Sistema de Gerenciamento de Papelaria"
        style="top: 0; left: 0; width: 75%;">
</div>
{% endblock %}

core/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:: PYPEL ::</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/crud.css' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    
</head>
<body>
    <div class="flex-wrapper">
        <header id="menu_navegacao">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                {% if request.session.perfil_atual == 'Administrador' or request.session.perfil_atual == 'Estoquista' or request.session.perfil_atual == 'Vendedor' %}
                <a class="navbar-brand" href="{% url 'core:main' %}">HOME</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        {% if request.session.perfil_atual == 'Administrador' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                MENU EXEMPLO
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="#">ITEM 1</a>
                                <a class="dropdown-item" href="#">ITEM 2</a>
                                <a class="dropdown-item" href="#">ITEM 3</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'autenticacao:logout' %}">
                                    <img src="{% static 'img/my_logout.png' %}" width="20px" alt="Logout">
                                    Sair
                                </a>
                            </div>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </nav>
        </header>

        <div class="content">
            {% block conteudo %}
            {% endblock %}
        </div>

        <!-- janela sobre -->
        <div class="modal fade" id="jnlSobre" tabindex="-1" role="dialog" aria-labelledby="jnlSobreRotulo" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="jnlSobreRotulo">Sobre o PYPEL</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-justify">
                        <p>
                            O PYPEL é um sistema de gerenciamento de papelaria que permite a gestão do estoque de produtos 
                            fornecendo um sistema de entrada e uma tela de venda que permite dar saída nos itens cadastrados no estoque.
                        </p>
                        <p>
                            O sistema é utilizado pelo Prof. Dr. Ciniro Nametala (<a href="http://lattes.cnpq.br/3258604768114823">lattes</a>) 
                            com o apoio das turmas da disciplina de Programação WEB do curso de Bacharelado em Engenharia de Computação do Instituto Federal de Minas Gerais - <i>Campus</i> Bambuí, e está licenciado sob 
                            <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
                                Licença Creative Commons&copy; 4.0 
                            </a> 
                            <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons">.
                        </p>
                        <p>
                            O PYPEL foi desenvolvido em <a href="https://www.python.org/" target="_blank" rel="noopener noreferrer">
                                Python
                            </a> <img src="{% static 'img/python.png' %}" width="15px" alt="Python">, 
                            <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django</a>
                            <img src="{% static 'img/django.png' %}" width="15px" alt="Django"> e 
                            <a href="https://www.postgresql.org/" target="_blank" rel="noopener noreferrer">PostgreSQL</a>
                            <img src="{% static 'img/postgresql.png' %}" width="15px" alt="PostgreSQL">. 
                            O código fonte, juntamente com as instruções de instalação, estão disponíveis para <i>download</i> em 
                            <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer">
                                github.com/ciniro/pypel
                            </a>
                            <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">. Você pode contribuir com o projeto, reportando erros, sugerindo melhorias ou mesmo implementando novas funcionalidades você mesmo. Por favor, use o GitHub para isso.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <footer id="rodape">
            <div class="footer-text text-align-center">
                PYPEL - Sistema de Gerenciamento de Papelaria <button id="btnSobre">Sobre</button><br>
                Este sistema está licenciado sob 
                <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer" style="color: #B0C4DE;">
                    Licença Creative Commons&copy; 4.0 
                </a> 
                <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons"> <br>
                Disponível para download em 
                <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer" style="color: #B0C4DE;">
                    github.com/ciniro/pypel
                </a>
                <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
            </div>
        </footer>
    </div>

    <script>
        //exibir modal sobre
        $('#btnSobre').click(function() {
            $('#jnlSobre').modal('show');
        });

        //eventos que serao usados no caso do cadastro ser carregado em forma modal
        window.addEventListener('load', function() {
            if (window.opener) {
                var header = document.getElementById('rodape');
                var footer = document.getElementById('menu_navegacao');
                
                if (header) header.style.display = 'none';
                if (footer) footer.style.display = 'none';
            }
        });

        window.onbeforeunload = function() {
            if (window.opener && !window.opener.closed) {
                window.opener.location.reload();
                window.opener.window.opener.desabilitaInteracoes();                
            }
        };
        //---------------------------------
        
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        toastr.error("{{ message }}", "Erro");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        toastr.success("{{ message }}", "Sucesso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        toastr.warning("{{ message }}", "Aviso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        toastr.info("{{ message }}", "Atenção");
                    {% endif %}
                {% endfor %}
            {% endif %}
        });
    </script>
</body>
</html>